name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install the project
      run: |
        uv sync --all-extras --dev
    - name: Analysing the code with pylint
      run: uv run pylint $(git ls-files '*.py')
    - name: Analysing the code with mypy
      run: uv run mypy --pretty --show-error-codes --show-error-context ./src
